server:
  port: 10004
redis:
  host: 106.75.246.168/
  port: 6380
  password: gsy123456
spring:
  webflux:
    multipart:
      headers-charset: UTF-8
  profiles:
    active: openai
logging:
  level:
    dev.langchain4j.model.openai: DEBUG